apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp     
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1 
  template: 
    metadata:
      labels:
        app: webapp     
    spec:
      containers:
        - name: webapp
          imagePullPolicy: Never
          image: test
          ports:
          - containerPort: 5000
          volumeMounts:
            - name: myvol
              mountPath:/app/webapp/html
      volumes:
        - name: myvol
          configMap:
            name: myconfigmap
