kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer
  volumeMounts:
    - name: myvol
      mountPath: /app/mytask/html
volumes:
   - name: myvol
     configMap:
       name: myconfigmap
